/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsMetricsRouteImport } from './routes/tools/metrics'
import { Route as ToolsCruiseCvCheckerRouteImport } from './routes/tools/cruise-cv-checker'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMetricsRoute = ToolsMetricsRouteImport.update({
  id: '/tools/metrics',
  path: '/tools/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCruiseCvCheckerRoute = ToolsCruiseCvCheckerRouteImport.update({
  id: '/tools/cruise-cv-checker',
  path: '/tools/cruise-cv-checker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tools/cruise-cv-checker': typeof ToolsCruiseCvCheckerRoute
  '/tools/metrics': typeof ToolsMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tools/cruise-cv-checker': typeof ToolsCruiseCvCheckerRoute
  '/tools/metrics': typeof ToolsMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/dashboard': typeof DashboardRoute
  '/landing': typeof LandingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tools/cruise-cv-checker': typeof ToolsCruiseCvCheckerRoute
  '/tools/metrics': typeof ToolsMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/dashboard'
    | '/landing'
    | '/sign-in'
    | '/sign-up'
    | '/tools/cruise-cv-checker'
    | '/tools/metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/dashboard'
    | '/landing'
    | '/sign-in'
    | '/sign-up'
    | '/tools/cruise-cv-checker'
    | '/tools/metrics'
  id:
    | '__root__'
    | '/'
    | '/builder'
    | '/dashboard'
    | '/landing'
    | '/sign-in'
    | '/sign-up'
    | '/tools/cruise-cv-checker'
    | '/tools/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuilderRoute: typeof BuilderRoute
  DashboardRoute: typeof DashboardRoute
  LandingRoute: typeof LandingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ToolsCruiseCvCheckerRoute: typeof ToolsCruiseCvCheckerRoute
  ToolsMetricsRoute: typeof ToolsMetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/metrics': {
      id: '/tools/metrics'
      path: '/tools/metrics'
      fullPath: '/tools/metrics'
      preLoaderRoute: typeof ToolsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/cruise-cv-checker': {
      id: '/tools/cruise-cv-checker'
      path: '/tools/cruise-cv-checker'
      fullPath: '/tools/cruise-cv-checker'
      preLoaderRoute: typeof ToolsCruiseCvCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuilderRoute: BuilderRoute,
  DashboardRoute: DashboardRoute,
  LandingRoute: LandingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ToolsCruiseCvCheckerRoute: ToolsCruiseCvCheckerRoute,
  ToolsMetricsRoute: ToolsMetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
